/**
 * ABDO HOUSE — Portfolio Projects Database
 * Connected to real MP4 video files in /assets/videos/
 */

export const PROJECTS_DATA = [
  {
    id: "monarch",
    num: "01",
    isFeatured: true,
    title: "MONARCH",
    subtitle: "Luxury Perfume Advertisement",
    category: "Fragrance / Cinematic 3D Film",
    year: "2026",
    badge: "CONCEPT PROJECT",
    isConcept: true,
    tagline: "The essence of nocturnal majesty.",
    video: "assets/videos/monarch.mp4",
    image: "assets/images/monarch.jpg",
    videoSrc: "assets/videos/monarch.mp4",
    posterSrc: "assets/images/monarch.jpg",
    visualType: "perfume",
    aspectRatio: "16/9",
    clientType: "Speculative Luxury Campaign",
    disciplines: ["Creative Direction", "3D Motion Design", "Fluid Dynamics", "Sound Design"],
    deliverables: "4K Master Film (60s), 9:16 Vertical Cutdowns, 8K Stills, Cinema Teaser",
    concept: "A cinematic visual identity inspired by royalty, darkness and sophistication. The composition captures the weightless alchemy of obsidian glass and micro-aerosol vapor under precision studio strobes, portraying fragrance as an armor of prestige.",
    creativeDirection: "Dark obsidian environments combined with champagne-gold highlights and dramatic studio lighting. Controlled chiaroscuro shadows emphasize bottle geometry and golden liquid viscosity.",
    palette: [
      { name: "Obsidian Black", hex: "#0B0B0D" },
      { name: "Charcoal Slate", hex: "#17171A" },
      { name: "Champagne Gold", hex: "#C9B27C" },
      { name: "Ivory Vapor", hex: "#F2EFE8" }
    ],
    process: [
      { step: "01", title: "Concept", desc: "Narrative architecture rooted in royal noir symbolism, dark glass silhouettes, and tactile luxury." },
      { step: "02", title: "Visual Development", desc: "High-contrast chiaroscuro lighting explorations and light refraction physics in simulated studio space." },
      { step: "03", title: "Visual Synthesis", desc: "Synthesizing ultra-high-resolution botanical smoke plumes, gilded particle trails, and obsidian reflections." },
      { step: "04", title: "Motion Design", desc: "Slow-motion 240fps fluid dynamics, vapor expansion physics, and precision 3D bottle rotation." },
      { step: "05", title: "Editing", desc: "Paced to editorial cadence with rhythmic micro-cuts, negative space tension, and sudden crescendo reveals." },
      { step: "06", title: "Sound Design", desc: "Spatial low-frequency sub-bass drones paired with crisp crystal resonance and breath-like aerosol release." }
    ]
  },
  {
    id: "royale-watch",
    num: "02",
    isFeatured: false,
    title: "ROYALE WATCH",
    subtitle: "Luxury Timepiece Advertisement",
    category: "Haute Horlogerie / 3D Film",
    year: "2026",
    badge: "CONCEPT PROJECT",
    isConcept: true,
    tagline: "The architecture of perpetual motion.",
    video: "assets/videos/royale-watch.mp4",
    image: "assets/images/royale-watch.jpg",
    videoSrc: "assets/videos/royale-watch.mp4",
    posterSrc: "assets/images/royale-watch.jpg",
    visualType: "watch",
    aspectRatio: "4/3",
    clientType: "Speculative Horology Campaign",
    disciplines: ["3D Hard-Surface Modeling", "Cinematic Lighting", "Kinematics", "Motion Editorial"],
    deliverables: "4K Commercial (90s), Boutique Installation Loop, Instagram Reel Suite",
    concept: "The poetry of mechanical time. A cinematic journey into a bespoke titanium tourbillon, illuminating every escapement wheel, jewel bearing, and hand-finished chamfer with surgical lighting precision.",
    creativeDirection: "Brushed titanium, matte carbon composite, and warm champagne-gold gear teeth. Anamorphic lens flare accents against obsidian black void with gold particle dust.",
    palette: [
      { name: "Obsidian Core", hex: "#0B0B0D" },
      { name: "Titanium Slate", hex: "#17171A" },
      { name: "Horology Gold", hex: "#C9B27C" },
      { name: "Platinum Ivory", hex: "#F2EFE8" }
    ],
    process: [
      { step: "01", title: "Concept", desc: "Treating mechanical complexity as architectural art and pure horological drama." },
      { step: "02", title: "Visual Development", desc: "CAD mechanical assembly breakdown, anisotropic brushed metal shader tuning." },
      { step: "03", title: "Visual Synthesis", desc: "Micro-texture generation for Damascus steel and synthetic sapphire crystal." },
      { step: "04", title: "Motion Design", desc: "Synchronized gear ratio kinematic animation and macro depth-of-field rack focus." },
      { step: "05", title: "Editing", desc: "Hypnotic, ticking rhythmic montage paired with sweeping anamorphic moves." },
      { step: "06", title: "Sound Design", desc: "Precision mechanical escapement clicks, metallic harmonics, and sweeping sub-woofs." }
    ]
  },
  {
    id: "delonghi",
    num: "03",
    isFeatured: false,
    title: "De'Longhi Magnifica S",
    subtitle: "Premium Espresso Machine Campaign",
    category: "Appliance & Beverage / Brand Film",
    year: "2026",
    badge: "CONCEPT PROJECT",
    isConcept: true,
    tagline: "Dark alchemy. Single-origin extraction.",
    video: "assets/videos/delonghi.mp4",
    image: "assets/images/delonghi.jpg",
    videoSrc: "assets/videos/delonghi.mp4",
    posterSrc: "assets/images/delonghi.jpg",
    visualType: "coffee",
    aspectRatio: "4/3",
    clientType: "Speculative Product Campaign",
    disciplines: ["High-Speed Fluid Simulation", "Macro Photography Direction", "Lighting", "Sound"],
    deliverables: "Brand Film (60s), E-commerce Header Video, 4K Social Teasers",
    concept: "Elevating bean-to-cup espresso to haute cuisine. Macro exploration of whole volcanic beans grinding, pressurized copper extraction, and rich amber crema pouring with millimeter precision.",
    creativeDirection: "Rich roasted obsidian tones, warm amber fluid illumination, and minimalist steam plumes creating an atmosphere of quiet morning luxury.",
    palette: [
      { name: "Volcanic Dark", hex: "#0B0B0D" },
      { name: "Roast Charcoal", hex: "#17171A" },
      { name: "Crema Amber", hex: "#C9B27C" },
      { name: "Porcelain Ivory", hex: "#F2EFE8" }
    ],
    process: [
      { step: "01", title: "Concept", desc: "Reframing espresso from routine morning caffeine to a luxurious meditative ritual." },
      { step: "02", title: "Visual Development", desc: "Fluid density simulations and vapor luminescence in dark moody space." },
      { step: "03", title: "Visual Synthesis", desc: "Hyper-detailed macro bean topography, roasting char patterns, and micro foam bubbles." },
      { step: "04", title: "Motion Design", desc: "High-speed extraction pour dynamics and slow-motion aromatic smoke dissipation." },
      { step: "05", title: "Editing", desc: "Sensory-led edit with slow hypnotic build-up and sharp final reveal." },
      { step: "06", title: "Sound Design", desc: "Rich bean crackle, pressurized steam release, and warm acoustic resonance." }
    ]
  },
  {
    id: "mintra",
    num: "04",
    isFeatured: false,
    title: "MINTRA CAI WIRE",
    subtitle: "Industrial Wire & Cable Product Film",
    category: "Industrial & Tech / 3D Product Film",
    year: "2026",
    badge: "CONCEPT PROJECT",
    isConcept: true,
    tagline: "Precision conductivity engineered for the future.",
    video: "assets/videos/mintra.mp4",
    image: "assets/images/mintra.jpg",
    videoSrc: "assets/videos/mintra.mp4",
    posterSrc: "assets/images/mintra.jpg",
    visualType: "fashion",
    aspectRatio: "16/10",
    clientType: "Speculative Industrial Campaign",
    disciplines: ["Industrial 3D Animation", "Material Physics", "Exploded CAD View", "Sound Design"],
    deliverables: "Commercial Master (60s), Trade Show Loop (4K), Technical Reel",
    concept: "Sculptural industrial precision. Transforming heavy-duty copper conduits and high-spec wire architecture into artful ribbons of energy coursing through dark monolithic space.",
    creativeDirection: "Raw brushed copper reflections, matte charcoal insulation jackets, and golden electrical wave arcs accentuating extreme durability.",
    palette: [
      { name: "Obsidian Void", hex: "#0B0B0D" },
      { name: "Industrial Slate", hex: "#17171A" },
      { name: "Copper Gold", hex: "#C9B27C" },
      { name: "Pure White", hex: "#F2EFE8" }
    ],
    process: [
      { step: "01", title: "Concept", desc: "Elevating industrial electrical infrastructure into sleek sculptural design." },
      { step: "02", title: "Visual Development", desc: "Cross-section CAD exploded diagrams and copper refraction studies." },
      { step: "03", title: "Visual Synthesis", desc: "Micro-texture generation for braided shielding and polymer flex patterns." },
      { step: "04", title: "Motion Design", desc: "Dynamic cable coiling physics, current pulse waves, and macro sweeps." },
      { step: "05", title: "Editing", desc: "High-energy industrial beat pacing with technical magnification cuts." },
      { step: "06", title: "Sound Design", desc: "Sub-bass electrical hum, high-voltage crackles, and resonant metallic hits." }
    ]
  },
  {
    id: "sony-xm6",
    num: "05",
    isFeatured: false,
    title: "Sony WH-1000XM6",
    subtitle: "Flagship Noise Canceling Headphones",
    category: "Consumer Tech / Motion Commercial",
    year: "2026",
    badge: "CONCEPT PROJECT",
    isConcept: true,
    tagline: "Silence redefined. Pure acoustic architecture.",
    video: "assets/videos/sony-xm6.mp4",
    image: "assets/images/sony-xm6.jpg",
    videoSrc: "assets/videos/sony-xm6.mp4",
    posterSrc: "assets/images/sony-xm6.jpg",
    visualType: "tech",
    aspectRatio: "1/1",
    clientType: "Speculative Technology Campaign",
    disciplines: ["Product Visualization", "Acoustic Wave Animation", "Lighting", "Mastering"],
    deliverables: "Product Reveal Film (60s), Social Media Hooks, 4K Display Stills",
    concept: "Monolithic audio engineering. Showing how next-generation active noise cancellation and soft-touch synthetic leather cushions isolate the listener in an oasis of sound.",
    creativeDirection: "Beveled matte black anodized surfaces, soft leather tactile close-ups, and pulsating golden acoustic frequency waves expanding into space.",
    palette: [
      { name: "Matte Obsidian", hex: "#0B0B0D" },
      { name: "Midnight Charcoal", hex: "#17171A" },
      { name: "Acoustic Gold", hex: "#C9B27C" },
      { name: "Ivory", hex: "#F2EFE8" }
    ],
    process: [
      { step: "01", title: "Concept", desc: "Visualizing the sensory sensation of complete silence and sonic clarity." },
      { step: "02", title: "Visual Development", desc: "Driver membrane displacement simulations and soft leather wrinkling shaders." },
      { step: "03", title: "Visual Synthesis", desc: "High-fidelity acoustic wave particle flows and brushed metal headband textures." },
      { step: "04", title: "Motion Design", desc: "Exploded driver assembly, headband flex dynamics, and orbital lighting passes." },
      { step: "05", title: "Editing", desc: "Rhythmic cut contrasts between chaotic outside noise and serene slow-motion isolation." },
      { step: "06", title: "Sound Design", desc: "Binaural 3D spatial audio, frequency sweep drops, and tactile click resonance." }
    ]
  },
  {
    id: "skin1004",
    num: "06",
    isFeatured: false,
    title: "SKIN1004 Madagascar Centella",
    subtitle: "Centella Skincare Product Campaign",
    category: "K-Beauty & Skincare / Commercial Film",
    year: "2026",
    badge: "CONCEPT PROJECT",
    isConcept: true,
    tagline: "Pure Madagascar Centella. Cellular calm.",
    video: "assets/videos/skin1004.mp4",
    image: "assets/images/skin1004.jpg",
    videoSrc: "assets/videos/skin1004.mp4",
    posterSrc: "assets/images/skin1004.jpg",
    visualType: "beauty",
    aspectRatio: "16/9",
    clientType: "Speculative Beauty Campaign",
    disciplines: ["Botanical Art Direction", "Viscous Fluid Simulation", "Macro Shading", "Color Grading"],
    deliverables: "Campaign Hero Film (45s), Retail Display Loops (8K), 9:16 Social Variations",
    concept: "An exploration of raw botanical purity and golden ampoule viscosity. We celebrate the golden amber hue of Madagascar Centella Asiatica flowing over cool volcanic stone.",
    creativeDirection: "Golden amber liquid droplets, soft diffused sunlight through morning fog, and tactile glass bottle reflections with minimal champagne-gold typography.",
    palette: [
      { name: "Volcanic Slate", hex: "#0B0B0D" },
      { name: "Warm Charcoal", hex: "#17171A" },
      { name: "Centella Amber", hex: "#C9B27C" },
      { name: "Botanical Ivory", hex: "#F2EFE8" }
    ],
    process: [
      { step: "01", title: "Concept", desc: "Deconstructing botanical purity into high-fashion sculptural geometry." },
      { step: "02", title: "Visual Development", desc: "Material studies on golden amber glass, dropper precision, and liquid surface tension." },
      { step: "03", title: "Visual Synthesis", desc: "Generating macro plant cell geometry and organic light caustic patterns." },
      { step: "04", title: "Motion Design", desc: "Surface tension simulations, weightless collision physics, and macro camera sweeps." },
      { step: "05", title: "Editing", desc: "Smooth liquid transitions designed for seamless looping on international screens." },
      { step: "06", title: "Sound Design", desc: "Ultra-crisp organic Foley, water droplet chimes, and ambient warm synth pads." }
    ]
  }
];
